services:
    phlexible_suggest.doctrine.data_source_manager:
        class: Phlexible\Bundle\SuggestBundle\Doctrine\DataSourceManager
        public: false
        arguments:
            - "@doctrine.orm.entity_manager"
