services:
    phlexible_suggest.garbage_collector:
        class: Phlexible\Bundle\SuggestBundle\GarbageCollector\GarbageCollector
        arguments:
            - "@phlexible_suggest.data_source_manager"
            - "@phlexible_suggest.value_collector"
            - "@event_dispatcher"
            - "@logger"
        tags:
            - {name: monolog.logger, channel: suggest}

    phlexible_suggest.element_version_checker:
        class: Phlexible\Bundle\SuggestBundle\Util\ElementVersionChecker
        arguments:
            - "@phlexible_element.element_service"
            - "@phlexible_tree.content_tree_manager"
            - "@phlexible_teaser.teaser_manager"

    phlexible_suggest.field.suggest:
        class: Phlexible\Bundle\SuggestBundle\Field\SuggestField
        public: false
        tags:
            - {name: phlexible_elementtype.field, alias: suggest}

    # controllers
    phlexible_suggest.data_sources_controller:
        class: Phlexible\Bundle\SuggestBundle\Controller\DataSourcesController
        arguments:
            - "@phlexible_suggest.data_source_manager"
            - "@security.token_storage"

    phlexible_suggest.field_controller:
        class: Phlexible\Bundle\SuggestBundle\Controller\FieldController
        arguments:
            - "@phlexible_suggest.data_source_manager"

    # event listeners
    phlexible_suggest.listener.apply_successor:
        class: Phlexible\Bundle\SuggestBundle\EventListener\ApplySuccessorListener
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - {name: kernel.event_listener, event: phlexible_user.apply_successor, method: onApplySuccessor}

    phlexible_suggest.listener.element_structure:
        class: Phlexible\Bundle\SuggestBundle\EventListener\ElementStructureListener
        arguments:
            - "@phlexible_suggest.data_source_manager"
            - "@phlexible_element.element_service"
        tags:
            - {name: kernel.event_subscriber}

    phlexible_suggest.listener.meta_set:
        class: Phlexible\Bundle\SuggestBundle\EventListener\MetaSetListener
        arguments:
            - "@phlexible_suggest.data_source_manager"
        tags:
            - {name: kernel.event_subscriber}

    # role provider
    phlexible_suggest.role_provider:
        class: Phlexible\Bundle\SuggestBundle\RoleProvider\SuggestRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}
