services:
    phlexible_suggest.garbage_collector:
        class: Phlexible\Bundle\SuggestBundle\GarbageCollector\GarbageCollector
        arguments:
            - "@phlexible_suggest.data_source_manager"
            - "@event_dispatcher"

    phlexible_suggest.element_suggest_field_util:
        class: Phlexible\Bundle\SuggestBundle\Util\ElementSuggestFieldUtil
        arguments:
            - "@phlexible_meta_set.meta_set_manager"
            - "@phlexible_element.element_service"
            - "@phlexible_element.element_source_manager"
            - "@phlexible_tree.content_tree_manager"
            - "@phlexible_teaser.teaser_manager"
            - "%phlexible_suggest.suggest_separator%"

    phlexible_suggest.element_meta_suggest_field_util:
        class: Phlexible\Bundle\SuggestBundle\Util\ElementMetaSuggestFieldUtil
        arguments:
            - "@phlexible_meta_set.meta_set_manager"
            - "@phlexible_element.element_meta_data_manager"
            - "%phlexible_suggest.suggest_separator%"

    phlexible_suggest.folder_meta_suggest_field_util:
        class: Phlexible\Bundle\SuggestBundle\Util\MediaMetaSuggestFieldUtil
        arguments:
            - "@phlexible_meta_set.meta_set_manager"
            - "@phlexible_media_manager.folder_meta_data_manager"
            - "%phlexible_suggest.suggest_separator%"

    phlexible_suggest.file_meta_suggest_field_util:
        class: Phlexible\Bundle\SuggestBundle\Util\MediaMetaSuggestFieldUtil
        arguments:
            - "@phlexible_meta_set.meta_set_manager"
            - "@phlexible_media_manager.file_meta_data_manager"
            - "%phlexible_suggest.suggest_separator%"

    # controllers
    phlexible_suggest.data_controller:
        class: Phlexible\Bundle\SuggestBundle\Controller\DataController
        arguments:
            - "@phlexible_suggest.data_source_manager"

    phlexible_suggest.field_controller:
        class: Phlexible\Bundle\SuggestBundle\Controller\FieldController
        arguments:
            - "@phlexible_suggest.data_source_manager"

    # event listeners
    phlexible_suggest.listener.apply_successor:
        class: Phlexible\Bundle\SuggestBundle\EventListener\ApplySuccessorListener
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - {name: kernel.event_listener, event: phlexible_user.apply_successor, method: onApplySuccessor}

    phlexible_suggest.listener.data_source:
        class: Phlexible\Bundle\SuggestBundle\EventListener\DataSourceListener
        arguments:
            -
                - "@phlexible_suggest.element_suggest_field_util"
                - "@phlexible_suggest.element_meta_suggest_field_util"
                - "@phlexible_suggest.file_meta_suggest_field_util"
                - "@phlexible_suggest.folder_meta_suggest_field_util"
        tags:
            - {name: kernel.event_subscriber}

    phlexible_suggest.listener.element_structure:
        class: Phlexible\Bundle\SuggestBundle\EventListener\ElementStructureListener
        arguments:
            - "@phlexible_suggest.data_source_manager"
            - "@phlexible_element.element_service"
        tags:
            - {name: kernel.event_subscriber}

    # role provider
    phlexible_suggest.role_provider:
        class: Phlexible\Bundle\SuggestBundle\RoleProvider\SuggestRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}
