services:
    phlexible_data_source.garbage_collector:
        class: Phlexible\Bundle\DataSourceBundle\GarbageCollector\GarbageCollector
        arguments:
            - "@phlexible_data_source.data_source_manager"
            - "@event_dispatcher"

    phlexible_data_source.element_suggest_field_util:
        class: Phlexible\Bundle\DataSourceBundle\Util\ElementSuggestFieldUtil
        arguments:
            - "@phlexible_meta_set.meta_set_manager"
            - "@phlexible_element.element_service"
            - "@phlexible_element.element_source_manager"
            - "@phlexible_tree.content_tree_manager"
            - "@phlexible_teaser.teaser_manager"
            - "%phlexible_data_source.suggest_separator%"

    phlexible_data_source.element_meta_suggest_field_util:
        class: Phlexible\Bundle\DataSourceBundle\Util\ElementMetaSuggestFieldUtil
        arguments:
            - "@phlexible_meta_set.meta_set_manager"
            - "@phlexible_element.element_meta_data_manager"
            - "%phlexible_data_source.suggest_separator%"

    phlexible_data_source.folder_meta_suggest_field_util:
        class: Phlexible\Bundle\DataSourceBundle\Util\MediaMetaSuggestFieldUtil
        arguments:
            - "@phlexible_meta_set.meta_set_manager"
            - "@phlexible_media_manager.folder_meta_data_manager"
            - "%phlexible_data_source.suggest_separator%"

    phlexible_data_source.file_meta_suggest_field_util:
        class: Phlexible\Bundle\DataSourceBundle\Util\MediaMetaSuggestFieldUtil
        arguments:
            - "@phlexible_meta_set.meta_set_manager"
            - "@phlexible_media_manager.file_meta_data_manager"
            - "%phlexible_data_source.suggest_separator%"

    # event listeners
    phlexible_data_source.listener.apply_successor:
        class: Phlexible\Bundle\DataSourceBundle\EventListener\ApplySuccessorListener
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - {name: kernel.event_listener, event: phlexible_user.apply_successor, method: onApplySuccessor}

    phlexible_data_source.listener.data_source:
        class: Phlexible\Bundle\DataSourceBundle\EventListener\DataSourceListener
        arguments:
            -
                - "@phlexible_data_source.element_suggest_field_util"
                - "@phlexible_data_source.element_meta_suggest_field_util"
                - "@phlexible_data_source.file_meta_suggest_field_util"
                - "@phlexible_data_source.folder_meta_suggest_field_util"
        tags:
            - {name: kernel.event_subscriber}

    phlexible_data_source.listener.element_structure:
        class: Phlexible\Bundle\DataSourceBundle\EventListener\ElementStructureListener
        arguments:
            - "@phlexible_data_source.data_source_manager"
            - "@phlexible_element.element_service"
        tags:
            - {name: kernel.event_subscriber}

    # role provider
    phlexible_data_source.role_provider:
        class: Phlexible\Bundle\DataSourceBundle\RoleProvider\DataSourceRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}
